Group7FinalProject/Group7FinalProject/Models/Reservation.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Group7FinalProject.Models
{
    //Enum for the status of a reservation
    public enum ReservationStatus {Valid, Cancelled, Unconfirmed}
    public class Reservation
    {
        //Constant Tax Rate of 7%
        private const Decimal TAX_RATE = 7.00m;

        //Creates the primary key for Reservation table
        public Int32 ReservationID { get; set; }

        [Display(Name = "Confirmation Number")]
        public Int32 ConfirmationNumber { get; set; }

        [Required(ErrorMessage = "Check-in date is required")]
        [DataType(DataType.Date)]
        [Display(Name = "Check-in Date")]
        public DateTime CheckIn {  get; set; }

        [Required(ErrorMessage = "Check-out date is required")]
        [DataType(DataType.Date)]
        [Display(Name = "Check-out Date")]
        public DateTime CheckOut { get; set; }

        [Required(ErrorMessage = "Number of guests is required")]
        [Range(1, int.MaxValue, ErrorMessage = "The value must be greater than 0.")]

        [Display(Name = "Number of guests")]
        //The number of guests staying
        public Int32 NumOfGuests { get; set; }

        [Display(Name = "Weekday price")]
        [Range(0, int.MaxValue, ErrorMessage = "The value must be non-negative.")]

        [DisplayFormat(DataFormatString = "{0:C}")]
        //Stores weekday price of reservation
        public Decimal WeekdayPrice { get; set; }

        [Display(Name = "Weekend price")]
        [Range(0, int.MaxValue, ErrorMessage = "The value must be non-negative.")]

        [DisplayFormat(DataFormatString = "{0:C}")]
        //Stores weekend price of reservation
        public Decimal WeekendPrice { get; set; }

        [Display(Name = "Cleaning Fee")]
        [Range(0, int.MaxValue, ErrorMessage = "The value must be non-negative.")]

        [DisplayFormat(DataFormatString = "{0:C}")]
        //Stores cleaning fee for reservation
        public Decimal CleaningFee {  get; set; }

        //Stores discount rate for reservation
        [Display(Name = "Discount Rate")]
        public Decimal DiscountRate { get; set; }

        [Display(Name = "Reservation Status")]
        //Stores enum for Status of Reservation
        public ReservationStatus ReservationStatus { get; set; }


        //Many side of One-To-Many relationship with Customer
        public AppUser? User { get; set; }

        //Many side of One-To-Many relationship with Property
        public Property? Property { get; set; }

        //Many side of One-To-Many relationship with Cart
        public Cart? Cart { get; set; }


        // Calculated values
        [NotMapped]
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Display(Name = "Weekday Total")]
        public decimal WeekdayTotal { get; private set; }

        [NotMapped]
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Display(Name = "Weekend Total")]
        public decimal WeekendTotal { get; private set; }

        [NotMapped]
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Display(Name = "Discount Amount")]
        public decimal DiscountAmount { get; private set; }

        [NotMapped]
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Display(Name = "Stay Price")]
        public decimal StayPrice { get; private set; }

        [NotMapped]
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Display(Name = "Subtotal")]
        public decimal SubTotal { get; private set; }

        [NotMapped]
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Display(Name = "Tax")]
        public decimal Tax { get; private set; }

        [NotMapped]
        [DisplayFormat(DataFormatString = "{0:C}")]
        [Display(Name = "Total Price")]
        public decimal TotalPrice { get; private set; }

        // Method to calculate totals
        public void CalcTotals()
        {
            // Calculate the number of days
            int totalDays = (CheckOut - CheckIn).Days;

            // Count weekdays and weekends
            int weekdayCount = 0, weekendCount = 0;
            for (DateTime date = CheckIn; date < CheckOut; date = date.AddDays(1))
            {
                if (date.DayOfWeek == DayOfWeek.Saturday || date.DayOfWeek == DayOfWeek.Sunday)
                {
                    weekendCount++;
                }
                else
                {
                    weekdayCount++;
                }
            }

            // Calculate weekday and weekend totals
            WeekdayTotal = weekdayCount * WeekdayPrice;
            WeekendTotal = weekendCount * WeekendPrice;

            // Calculate discount
            if (totalDays >= Property?.MinNightsForDiscount)
            {
                DiscountAmount = (WeekdayTotal + WeekendTotal) * DiscountRate;
            }
            else
            {
                DiscountAmount = 0;
            }

            // Calculate stay price
            StayPrice = (WeekdayTotal + WeekendTotal) - DiscountAmount;

            // Calculate subtotal
            SubTotal = StayPrice + CleaningFee;

            // Calculate tax
            Tax = SubTotal * (TAX_RATE/100);

            // Calculate total price (reservation total)
            TotalPrice = SubTotal + Tax;
        }

    }


}

Group7FinalProject/Group7FinalProject/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Group7FinalProject.DAL;
using Group7FinalProject.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data.Common;
using Microsoft.AspNetCore.Identity;

namespace Group7FinalProject.Controllers
    
{

    public class ReservationsController : Controller
    {

        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;


        public ReservationsController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Reservations
        [Authorize(Roles = "Customer, Host, Admin")]
        public async Task<IActionResult> Index()
        {
            // Set up a list of reservations to display
            List<Reservation> reservations;

            // Check user role and filter reservations accordingly
            if (User.IsInRole("Host"))
            {
                reservations = _context.Reservations
                                .Include(r => r.Property)
                                .Where(r => r.Property.User.UserName == User.Identity.Name)
                                .Where(r => r.ReservationStatus == ReservationStatus.Valid || r.ReservationStatus == ReservationStatus.Cancelled)
                                                        .OrderBy(r => r.CheckIn) // Sort by Check-In date

                                .ToList();
            }
            else
            {
                // User is a customer, so only display their records
                reservations = _context.Reservations
                                .Include(r => r.Property)
                                .Where(r => r.User.UserName == User.Identity.Name)
                                .Where(r => r.ReservationStatus == ReservationStatus.Valid || r.ReservationStatus == ReservationStatus.Cancelled)
                                                        .OrderBy(r => r.CheckIn) // Sort by Check-In date

                                .ToList();
            }

            foreach (var reservation in reservations)
            {
                reservation.CalcTotals();
            }

            // Check if the reservations list is empty
            if (reservations == null || !reservations.Any())
            {
                // Return a view with a message indicating no reservations
                ViewBag.Message = "You have not made any reservations yet. Please browse our properties and make a reservation to see it here.";
                return View("NoReservations");
            }

            // Return the list of reservations if there are any
            return View(reservations);
        }


        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //the user did not specify a reservation to view
            if (id == null)
            {
                return View("Error", new String[] { "Please specify a reservation to view!" });
            }

            //find the reservation in the database
            Reservation reservation = await _context.Reservations
                                              .Include(r => r.Property)
                                              .Include(r => r.User)
                                              .FirstOrDefaultAsync(m => m.ReservationID == id);

            //reservation was not found in the database
            if (reservation == null)
            {
                return View("Error", new String[] { "This reservation was not found!" });
            }

            //make sure this order belongs to this user
            if (User.IsInRole("Customer") && reservation.User.UserName != User.Identity.Name)
            {
                return View("Error", new String[] { "This is not your reservation!  Don't be such a snoop!" });
            }

            reservation.CalcTotals();

            //Send the user to the details page
            return View(reservation);
        }

        [Authorize(Roles = "Customer, Admin")]

        public async Task<IActionResult> Create(int? PropertyID)
        {

            if (PropertyID == null)
            {
                return View("Error", new string[] { "Please specify a property to add to the reservation" });
            }

            //find the property in the database
            Property dbProperty = _context.Properties.Find(PropertyID);

            //make sure the Property exists in the database
            if (dbProperty == null)
            {
                return View("Error", new string[] { "This Property was not in the database!" });
            }

            if (User.IsInRole("Admin"))
            {
                ViewBag.UserNames = await GetAllCustomerUserNamesSelectList();
                return View("SelectCustomerForReservation", new Reservation { Property = dbProperty });
            }

            Reservation res = new Reservation();
            res.Property = dbProperty;
            res.CheckIn = DateTime.Today.AddDays(1); // Default check-in
            res.CheckOut = DateTime.Today.AddDays(2); // Default check-out
            res.User = await _userManager.FindByNameAsync(User.Identity.Name);


            return View(res);

        }





        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Customer,Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Reservation reservation, int propertyID, string? SelectedCustomer)
        {


            
            if (!ModelState.IsValid)
            {
                // Fetch the property details to repopulate the reservation model
                Property testProperty = await _context.Properties.Include(p => p.User).FirstOrDefaultAsync(p => p.PropertyID == propertyID);
                if (testProperty == null)
                {
                    return View("Error", new string[] { "The property could not be found." });
                }

                // Repopulate the property in the reservation model
                reservation.Property = testProperty;

                // Return the view with the current reservation model
                return View(reservation);
            }

            //find the property to be associated with this reservation
            Property dbProperty = _context.Properties.Find(propertyID);

            reservation.Property = dbProperty;

            if (dbProperty == null)
            {
                return View("Error", new string[] { "The property could not be found." });
            }

            // Validate the number of guests against the property's guest limit
            if (reservation.NumOfGuests > dbProperty.GuestsAllowed)
            {
                return View("Error", new string[] { $"The number of guests exceeds the property's limit of {dbProperty.GuestsAllowed}." });
            }

            // Load the User
            if (User.IsInRole("Customer"))
            {
                reservation.User = await _userManager.FindByNameAsync(User.Identity.Name);
                if (reservation.User == null)
                {
                    return View("Error", new string[] { "The user could not be found." });
                }

            }
            //If user is an admin, make reservation user the parameter
            if (User.IsInRole("Admin"))
            {
                reservation.User = await _userManager.FindByNameAsync(SelectedCustomer);
                if (reservation.User == null)
                {
                    return View("Error", new string[] { "The user could not be found." });
                }
            }

            // Validate CheckIn and CheckOut dates
            if (reservation.CheckIn <= DateTime.Today)
            {
                return View("Error", new string[] { "Check-in date must be in the future." });
            }

            if (reservation.CheckOut <= reservation.CheckIn)
            {
                return View("Error", new string[] { "Check-out date must be after the check-in date." });
            }

            // Retrieve reservations for the specified property
            List<Reservation> reservations = await _context.Reservations
                .Include(r => r.Property)
                .Where(r => r.Property.PropertyID == propertyID)
                .ToListAsync();

            // Check for overlapping reservations
            if (reservations.Count(r =>
             (reservation.CheckIn >= r.CheckIn && reservation.CheckIn < r.CheckOut) || // Overlaps on check-in
             (reservation.CheckOut > r.CheckIn && reservation.CheckOut <= r.CheckOut) || // Overlaps on check-out
             (reservation.CheckIn <= r.CheckIn && reservation.CheckOut >= r.CheckOut)) > 0) // Completely overlaps
            {
                return View("Error", new string[] { "The reservation dates overlap with an existing reservation for this property." });
            }

            // Fetch reservations for the same user
            List<Reservation> userReservations = await _context.Reservations
                .Where(r => r.User.UserName == User.Identity.Name) // Match the current user
                .ToListAsync();

            // Check for overlapping reservations for the same user
            if (userReservations.Count(r =>
                (reservation.CheckIn >= r.CheckIn && reservation.CheckIn < r.CheckOut) || // Overlaps on check-in
                (reservation.CheckOut > r.CheckIn && reservation.CheckOut <= r.CheckOut) || // Overlaps on check-out

Group7FinalProject/Group7FinalProject/Views/Reservations/Confirmation.cshtml
@model Group7FinalProject.Models.Reservation

@{
    ViewData["Title"] = "Reservation Confirmation";
}

<h2>Reservation Confirmation</h2>

<p>Thank you for your reservation! Below is your confirmation number and the details of your reservation:</p>
<p><strong>Confirmation Number:</strong> @ViewBag.ConfirmationNumber</p>

<!-- Reservation Details Table -->
<table class="table">
    <thead>
        <tr>
            <th>Property</th>
            <th>Check-In Date</th>
            <th>Check-Out Date</th>
            <th>Number of Guests</th>
            <th>Weekday Total</th>
            <th>Weekend Total</th>
            <th>Discount</th>
            <th>Stay Price</th>
            <th>Cleaning Fee</th>
            <th>Subtotal</th>
            <th>Tax</th>
            <th>Total Price</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Property.PropertyNumber</td>
            <td>@Model.CheckIn.ToShortDateString()</td>
            <td>@Model.CheckOut.ToShortDateString()</td>
            <td>@Model.NumOfGuests</td>
            <td>@Model.WeekdayTotal.ToString("C")</td>
            <td>@Model.WeekendTotal.ToString("C")</td>
            <td>@Model.DiscountAmount.ToString("C")</td>
            <td>@Model.StayPrice.ToString("C")</td>
            <td>@Model.CleaningFee.ToString("C")</td>
            <td>@Model.SubTotal.ToString("C")</td>
            <td>@Model.Tax.ToString("C")</td>
            <td>@Model.TotalPrice.ToString("C")</td>
        </tr>
    </tbody>
</table>

<!-- Navigation Options -->
<div>
    <a asp-action="Index" asp-controller="Properties" class="btn btn-warning">Return to Home</a>
    @if (User.Identity.IsAuthenticated && User.IsInRole("Customer"))
    {
        <a asp-controller="Reservations" asp-action="Index" class="btn btn-primary">View My Reservations</a>
    }
</div>

Group7FinalProject/Group7FinalProject/Views/Reservations/Create.cshtml
@model Group7FinalProject.Models.Reservation

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input type="hidden" name="propertyID" value="@Model.Property?.PropertyID" />
            <input type="hidden" name="SelectedCustomer" value="@Model.User?.UserName" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="CheckIn" class="control-label"></label>
                <input asp-for="CheckIn" class="form-control" />
                <span asp-validation-for="CheckIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckOut" class="control-label"></label>
                <input asp-for="CheckOut" class="form-control" />
                <span asp-validation-for="CheckOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumOfGuests" class="control-label"></label>
                <input asp-for="NumOfGuests" class="form-control" />
                <span asp-validation-for="NumOfGuests" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Group7FinalProject/Group7FinalProject/Views/Reservations/Details.cshtml
@model Group7FinalProject.Models.Reservation

@{
    ViewData["Title"] = "Reservation Details";
}

<h1>Reservation Details</h1>

<!-- Table to display reservation details -->
<table class="table">
    <thead>
        <tr>
            <th>Property</th>
            <th>Check-In Date</th>
            <th>Check-Out Date</th>
            <th>Number of Guests</th>
            <th>Weekday Total</th>
            <th>Weekend Total</th>
            <th>Discount Amount</th>
            <th>Stay Price</th>
            <th>Cleaning Fee</th>
            <th>Subtotal</th>
            <th>Tax</th>
            <th>Total Price</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Property?.PropertyNumber</td>
            <td>@Model.CheckIn.ToShortDateString()</td>
            <td>@Model.CheckOut.ToShortDateString()</td>
            <td>@Model.NumOfGuests</td>
            <td>@Model.WeekdayTotal.ToString("C")</td>
            <td>@Model.WeekendTotal.ToString("C")</td>
            <td>@Model.DiscountAmount.ToString("C")</td>
            <td>@Model.StayPrice.ToString("C")</td>
            <td>@Model.CleaningFee.ToString("C")</td>
            <td>@Model.SubTotal.ToString("C")</td>
            <td>@Model.Tax.ToString("C")</td>
            <td>@Model.TotalPrice.ToString("C")</td>
        </tr>
    </tbody>
</table>

<table class="table table-primary">
    <tr>
        <th>Property Address</th>
        <th>Beds</th>
        <th>Bathrooms</th>
        <th>Guests Allowed</th>
        <th>Pet Friendly</th>
        <th>Parking Available</th>
    </tr>
    <tr>
        <td>@($"{Model.Property.Address}, {Model.Property.City}, {Model.Property.State} {Model.Property.ZipCode}")</td>
        <td>@Html.DisplayFor(ModelItem => Model.Property.NumOfBedrooms)</td>
        <td>@Html.DisplayFor(ModelItem => Model.Property.NumOfBathrooms)</td>
        <td>@Html.DisplayFor(ModelItem => Model.Property.GuestsAllowed)</td>
        <td>@Html.DisplayFor(ModelItem => Model.Property.PetFriendly)</td>
        <td>@Html.DisplayFor(ModelItem => Model.Property.HasParking)</td>
    </tr>
</table>

<div>
    <!-- Conditionally show the Cancel button if the reservation is valid -->
    @if (Model.ReservationStatus == ReservationStatus.Valid && Model.CheckIn > DateTime.Now)
    {
        <a asp-action="CancelReservation" asp-route-id="@Model.ReservationID" class="btn btn-danger">Cancel</a>
    }

    @if (User.Identity.IsAuthenticated && User.IsInRole("Customer"))
    {
        <a asp-controller="Reviews" asp-action="Create" asp-route-propertyId="@Model.Property.PropertyID" class="btn btn-primary">
            Write Review
        </a>
    }

    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</div>

Group7FinalProject/Group7FinalProject/Views/Reservations/Edit.cshtml
@model Group7FinalProject.Models.Reservation

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Reservation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReservationID" />
            <div class="form-group">
                <label asp-for="ConfirmationNumber" class="control-label"></label>
                <input asp-for="ConfirmationNumber" class="form-control" />
                <span asp-validation-for="ConfirmationNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckIn" class="control-label"></label>
                <input asp-for="CheckIn" class="form-control" />
                <span asp-validation-for="CheckIn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CheckOut" class="control-label"></label>
                <input asp-for="CheckOut" class="form-control" />
                <span asp-validation-for="CheckOut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumOfGuests" class="control-label"></label>
                <input asp-for="NumOfGuests" class="form-control" />
                <span asp-validation-for="NumOfGuests" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WeekdayPrice" class="control-label"></label>
                <input asp-for="WeekdayPrice" class="form-control" />
                <span asp-validation-for="WeekdayPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WeekendPrice" class="control-label"></label>
                <input asp-for="WeekendPrice" class="form-control" />
                <span asp-validation-for="WeekendPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CleaningFee" class="control-label"></label>
                <input asp-for="CleaningFee" class="form-control" />
                <span asp-validation-for="CleaningFee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DiscountRate" class="control-label"></label>
                <input asp-for="DiscountRate" class="form-control" />
                <span asp-validation-for="DiscountRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReservationStatus" class="control-label"></label>
                <select asp-for="ReservationStatus" class="form-control"></select>
                <span asp-validation-for="ReservationStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Group7FinalProject/Group7FinalProject/Views/Reservations/Index.cshtml
@model IEnumerable<Group7FinalProject.Models.Reservation>

@{
    ViewData["Title"] = "Reservations";
}

<h1>Reservations</h1>

<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th>@Html.DisplayNameFor(model => model.First().ConfirmationNumber)</th>
                @if (User.Identity.IsAuthenticated && User.IsInRole("Host"))
                {
                    <th>@Html.DisplayNameFor(model => model.First().Property.PropertyNumber)</th>
                }
                <th>@Html.DisplayNameFor(model => model.First().CheckIn)</th>
                <th>@Html.DisplayNameFor(model => model.First().CheckOut)</th>
                <th>@Html.DisplayNameFor(model => model.First().NumOfGuests)</th>
                <th>@Html.DisplayNameFor(model => model.First().WeekdayTotal)</th>
                <th>@Html.DisplayNameFor(model => model.First().WeekendTotal)</th>
                <th>@Html.DisplayNameFor(model => model.First().DiscountAmount)</th>
                <th>@Html.DisplayNameFor(model => model.First().StayPrice)</th>
                <th>@Html.DisplayNameFor(model => model.First().CleaningFee)</th>
                <th>@Html.DisplayNameFor(model => model.First().SubTotal)</th>
                <th>@Html.DisplayNameFor(model => model.First().Tax)</th>
                <th>@Html.DisplayNameFor(model => model.First().TotalPrice)</th>
                <th>@Html.DisplayNameFor(model => model.First().ReservationStatus)</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.ConfirmationNumber)</td>
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Host"))
                    {
                        <td>@(item.Property != null ? item.Property.PropertyNumber : "N/A")</td>
                    }
                    <td>@Html.DisplayFor(modelItem => item.CheckIn)</td>
                    <td>@Html.DisplayFor(modelItem => item.CheckOut)</td>
                    <td>@Html.DisplayFor(modelItem => item.NumOfGuests)</td>
                    <td>@item.WeekdayTotal.ToString("C")</td>
                    <td>@item.WeekendTotal.ToString("C")</td>
                    <td>@item.DiscountAmount.ToString("C")</td>
                    <td>@item.StayPrice.ToString("C")</td>
                    <td>@item.CleaningFee.ToString("C")</td>
                    <td>@item.SubTotal.ToString("C")</td>
                    <td>@item.Tax.ToString("C")</td>
                    <td>@item.TotalPrice.ToString("C")</td>
                    <td>@Html.DisplayFor(modelItem => item.ReservationStatus)</td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ReservationID">Details</a>
                        @if (item.ReservationStatus == ReservationStatus.Valid && item.CheckIn > DateTime.Now)
                        {
                            <a asp-action="CancelReservation" asp-route-id="@item.ReservationID">| Cancel</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Group7FinalProject/Group7FinalProject/Views/Reservations/NoReservations.cshtml
@{
    ViewData["Title"] = "No Reservations";
}

<h1>No Reservations</h1>
<p>@ViewBag.Message</p>

<a asp-action="Index" asp-controller="Properties">Browse Properties</a>

Group7FinalProject/Group7FinalProject/Views/Reservations/SelectCustomerForReservation.cshtml
@model Group7FinalProject.Models.Reservation

@{
    ViewData["Title"] = "Select a Customer";
}

<h1>Select the Customer for the Order</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SelectCustomerForReservation" method="post">
            <input type="hidden" name="propertyID" value="@Model.Property.PropertyID" />


            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">All Customers:</label>
                @Html.DropDownList("SelectedCustomer", (SelectList)@ViewBag.UserNames, new { @class = "form-control" })
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Select Customer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>